### ISSUE TITLE
照readme的流程跑了一下，报了这个错，看起来是worker未启动？address 0.0.0.0:54397. Head or worker may be down.

### ISSUE THREAD

**Issue by JessyTsui** [ArthurKing01/jina-clip#1]
ERROR  gateway/rep-0@12947 Error while getting responses
       from deployments: failed to connect to all addresses                     
       |Gateway: Communication error with deployment at                         
       address 0.0.0.0:54397. Head or worker may be down.

**Comment by JessyTsui** [comment]
补充一下，页面正常OK了，调用search接口的时候报的错，因为不太熟悉tornado用的什么worker所以想问一下

**Comment by ArthurKing01** [comment]
上传正常吗，在`yarn start`后可以等待1分钟左右试试，看样子是Jina未正常启动

**Comment by alili** [comment]
<img width="371" alt="image" src="https://user-images.githubusercontent.com/4102907/175960482-18d4dd26-b68e-4e46-b317-d0894a79b594.png">
启动以后应该会在控制台看到这个

**Comment by JessyTsui** [comment]
ok了，确实得等jina启动...
